version: '3.7'

services:
  zookeeper:
    image: ${ZK_IMAGE}:${ZK_VERSION}
    container_name: zookeeper
    ports:
      - "${ZK_PORT}:2181"
    volumes:
      - ${CONFIG_DIR}/zookeeper/zoo.cfg:/conf/zoo.cfg
      - ${VOLUMES_DIR}/zookeeper/data:/data
      - ${VOLUMES_DIR}/zookeeper/datalog:/datalog

  ch1:
    image: ${CH_IMAGE}:${CH_VERSION}
    container_name: ch1
    hostname: ch1
    volumes:
      - ${CONFIG_DIR}/clickhouse/node1/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${VOLUMES_DIR}/clickhouse/node1:/var/lib/clickhouse
    ports:
      - "${CH1_NATIVE_PORT}:9000"
      - "${CH1_HTTP_PORT}:8123"
    depends_on:
      - zookeeper

  ch2:
    image: ${CH_IMAGE}:${CH_VERSION}
    container_name: ch2
    hostname: ch2
    volumes:
      - ${CONFIG_DIR}/clickhouse/node2/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${VOLUMES_DIR}/clickhouse/node2:/var/lib/clickhouse
    ports:
      - "${CH2_NATIVE_PORT}:9000"
      - "${CH2_HTTP_PORT}:8123"
    depends_on:
      - zookeeper

  ch3:
    image: ${CH_IMAGE}:${CH_VERSION}
    container_name: ch3
    hostname: ch3
    volumes:
      - ${CONFIG_DIR}/clickhouse/node3/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${VOLUMES_DIR}/clickhouse/node3:/var/lib/clickhouse
    ports:
      - "${CH3_NATIVE_PORT}:9000"
      - "${CH3_HTTP_PORT}:8123"
    depends_on:
      - zookeeper

  ch4:
    image: ${CH_IMAGE}:${CH_VERSION}
    container_name: ch4
    hostname: ch4
    volumes:
      - ${CONFIG_DIR}/clickhouse/node4/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${VOLUMES_DIR}/clickhouse/node4:/var/lib/clickhouse
    ports:
      - "${CH4_NATIVE_PORT}:9000"
      - "${CH4_HTTP_PORT}:8123"
    depends_on:
      - zookeeper

  haproxy:
    image: ${HAPROXY_IMAGE}:${HAPROXY_VERSION}
    container_name: haproxy
    volumes:
      - ${CONFIG_DIR}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "${HAPROXY_NATIVE_PORT}:9000"
      - "${HAPROXY_HTTP_PORT}:8123"
    depends_on:
      - ch1
      - ch2
      - ch3
      - ch4
